## The press that missed by a hair: a sphere the size of the tool in the player's
## hand, swept down the aim, so a ray that went just over the roof still lands on
## the roof — on real paint, with the paint's own normal.
##
## [b]What was wrong before this, and it is not what it looks like.[/b] The room
## has never had trouble [i]finding[/i] the car when a press misses it:
## [NearestPoint] answers "which panel did I come closest to" for any aim
## whatsoever, and [method Garage._nearest_on_the_car] then plants a post at the
## nearest point on that panel's box and casts a second ray at it. What that pair
## cannot always produce is a place with a [i]measured normal[/i] — and a measured
## normal is the one thing [method Garage._spend_the_trigger] cannot do without,
## because [BoxProjection] picks which face of a panel to write to by reading it.
## So when the post's probe misses too, the answer comes back flagged
## [code]surface: false[/code], the tool draws its water and its foam on the mark,
## and the grime is never touched. A tool that visibly runs and cleans nothing is
## the same failure [method Garage._spend_the_trigger] already has a paragraph
## about — it just arrives down a different path.
##
## [b]So the win here is narrow and worth stating exactly.[/b] This does not find
## the car more often. It converts misses that would have been answered
## [code]surface: false[/code] into real hits that can be worked. The press it was
## built for is the one the game creates for itself: [ThumbLift] deliberately
## takes the aim a thumb's width up the glass from the finger, and a thumb on the
## flank of a low car routinely sends the ray just over the roofline — a sport car
## is 1.04 m tall and the blockout this was measured on was 1.4 m. The wheel
## arches and the gap between a tyre and its sill are the same shape of problem
## from the other direction — geometry thin enough for a zero-width ray to
## thread.
##
## [b]It is not the primary query, and that is deliberate.[/b] A swept sphere
## stops at the first thing it touches, which is not the same as the thing you
## were pointing at: aim at a door from slightly above and the sphere clips the
## roof edge on its way past, and the mark lands on the roof. Run as the only
## query it would be strictly worse than the exact ray at every grazing angle. So
## [method Garage._under_the_finger] keeps [method
## PhysicsDirectSpaceState3D.intersect_ray] first and reaches for this only once
## that has come back empty — which is to say, only when there is no exact answer
## to steal from.
##
## [b]Why the radius is the tool's own[/b] rather than a tuning constant of its
## own. The window the sweep opens is exactly the window the player can already
## see: [member Garage.wash_radius_metres] is the patch [WashJet]'s water lands
## on, and [member Garage.scrub_radius_metres] is the ring [SpongeSuds]'s foam is
## squeezed out to. Forgiving the aim by the width of the brush is a rule a player
## can read off the screen without being told it. A separate number would be a
## second opinion about how big a tool is, in the one place it could disagree with
## the picture.
##
## [b]Two engine calls, because neither one of them is the whole question.[/b]
## [method PhysicsDirectSpaceState3D.cast_motion] sweeps but answers only in
## fractions — no point, no normal, no collider. [method
## PhysicsDirectSpaceState3D.get_rest_info] answers all three but does not sweep.
## So the shape is cast to find out [i]how far[/i], parked where that says, and
## asked what it is resting on. Both halves were checked against the real car
## rather than taken from the docs, because the car's colliders are concave
## trimeshes generated by [member CSGShape3D.use_collision] and convex-versus-
## concave is exactly the pairing that quietly returns nothing in some engines:
## measured, a sweep at the roofline comes back
## [code][0.0596, 0.0625][/code] and rests on [code]Windshield[/code] with a
## normal of [code](0.00, 0.84, 0.54)[/code] — the real face, pointing out of it.
##
## [b]An instance and not a static, unlike [NearestPoint][/b], which is the one
## place these two differ in shape. The shape and the query are engine objects
## that would otherwise be allocated twice per physics tick for the whole time a
## finger is dragging across the sky, and they carry no state between calls worth
## the name — every field either code path reads is written before it is read. So
## the room builds one alongside the sight and keeps it.
##
## [b]In [code]src/world/[/code] and not [code]src/core/[/code][/b], because it
## queries a physics space and a space state only exists in a running scene. That
## is the R3 line in STANDARDS.md "Coverage" drawn where it is meant to be: this
## is tested at the integration tier, against a real car, in
## [code]tests/integration/test_play_screen_sweep.gd[/code].
class_name AimSweep
extends RefCounted

## What [method PhysicsDirectSpaceState3D.cast_motion] answers when the shape
## reached the end of its sweep without touching anything — measured, not assumed:
## it returns [code][1.0, 1.0][/code] for a sphere thrown at the sky.
##
## A named constant because the reading is not obvious. The pair is
## [code][safe, unsafe][/code] and both are fractions of the motion, so "nothing
## was hit" and "something was hit at the very last millimetre" are told apart by
## a strict comparison against this and nothing else.
const NOTHING_HIT: float = 1.0

var _reach: float
var _ball: SphereShape3D = SphereShape3D.new()
var _query: PhysicsShapeQueryParameters3D = PhysicsShapeQueryParameters3D.new()


## Built with how far the aim carries, in metres — [member Garage.aim_reach], the
## same distance the exact ray is cast, because this is the same aim asked a wider
## question rather than a different one.
func _init(reach: float) -> void:
	_reach = reach
	_query.shape = _ball


## Where a sphere of [param radius] swept from [param origin] along
## [param direction] first touches the world, or an empty [Dictionary] if it
## touches nothing.
##
## Shaped like the engine's own [method PhysicsDirectSpaceState3D.intersect_ray]
## result — [code]position[/code], [code]normal[/code], [code]collider[/code] —
## plus the [code]surface[/code] key [method Garage._under_the_finger] reads, so
## that all three of its tiers hand back one shape and a caller cannot forget
## which one it is holding. It is set here rather than by the caller, and it is
## always true: every field of this answer came off real geometry, which is the
## entire reason the tier exists. The engine's own keys are renamed on the way out
## — [code]point[/code] and [code]collider_id[/code] are what a rest query calls
## them — because agreeing with the raycast is the whole point.
##
## [b]Parked at the unsafe fraction and not the safe one.[/b] The safe fraction is
## the last position where the shape is provably clear, and a shape that is clear
## is resting on nothing — [method PhysicsDirectSpaceState3D.get_rest_info] would
## answer empty for the sweep that just succeeded. The unsafe fraction is the
## first position where it is touching, which is the contact being asked about.
##
## [b]A radius of nothing is refused rather than swept[/b], because a sphere with
## no size is the ray that has already been cast and missed: the engine would
## answer the same nothing a little more slowly, and a tool whose reach was
## misconfigured to zero would silently get the old behaviour instead of an
## obviously wrong one.
func onto(
	space: PhysicsDirectSpaceState3D, origin: Vector3, direction: Vector3, radius: float
) -> Dictionary:
	if radius <= 0.0:
		return {}
	var travel: Vector3 = direction.normalized() * _reach
	_ball.radius = radius
	_query.transform = Transform3D(Basis(), origin)
	_query.motion = travel
	var fractions: PackedFloat32Array = space.cast_motion(_query)
	if fractions.size() < 2 or fractions[1] >= NOTHING_HIT:
		return {}
	_query.transform = Transform3D(Basis(), origin + travel * fractions[1])
	# Cleared before the rest query so the parked shape is asked what it is
	# touching *there* rather than being swept a second time from there.
	_query.motion = Vector3.ZERO
	var rest: Dictionary = space.get_rest_info(_query)
	if rest.is_empty():
		return {}
	# Read out into typed locals rather than passed straight through: a
	# [Dictionary] hands back [Variant], and this project's warning levels treat
	# handing one to a typed parameter as an error rather than as a cast.
	var who: int = rest["collider_id"]
	var panel: Object = instance_from_id(who)
	if panel == null:
		return {}
	var point: Vector3 = rest["point"]
	var facing: Vector3 = rest["normal"]
	return {
		"position": point,
		"normal": facing,
		"collider": panel,
		"surface": true,
	}
